Repository feature-sliced/documentation, pull requests merged in 2021-08, with the labels that each got.

#237 Исправление опечаток
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/needs-driven.md
Labels: TYPE | bug

#240 Добавил базовый перевод доки (part 1)
  website/docusaurus.config.js
  website/i18n/en/code.json
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/app-splitting.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/architecture.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/cross-communication.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/naming-adaptability.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/needs-driven.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/public-api.md
  website/i18n/en/docusaurus-plugin-content-docs/current/guides/low-coupling.md
  website/i18n/en/docusaurus-plugin-content-docs/current/guides/migration-from-v1.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/knowledge-types.md
  website/i18n/en/docusaurus-theme-classic/footer.json
  website/i18n/ru/code.json
  website/i18n/ru/docusaurus-plugin-content-docs/current.json
  website/i18n/ru/docusaurus-plugin-content-docs/current/about/community.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/about/history.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/about/mission.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/app-splitting.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/architecture.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/cross-communication.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/naming-adaptability.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/needs-driven.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/basics.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/motivation.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/overview.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/quick-start.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/guides/low-coupling.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/guides/migration-from-v1.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/readme.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/glossary.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/knowledge-types.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/layers/overview.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/segments.md
  website/i18n/ru/docusaurus-theme-classic/footer.json
  website/i18n/ru/docusaurus-theme-classic/navbar.json
  website/src/features/header/ui.jsx
  website/src/pages/_config.jsx
  website/src/pages/examples/index.jsx
  website/src/pages/index.jsx
  website/src/pages/versions.jsx
Labels: TYPE | workflow

#241 Добавил базовый перевод доки (part 2)
  .github/workflows/deploy.yml
  .github/workflows/testing.yml
  README.md
  website/docusaurus.config.js
  website/i18n/en/docusaurus-plugin-content-docs/current/about/mission.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/app-splitting.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/architecture.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/cross-communication.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/naming-adaptability.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/needs-driven.md
  website/i18n/en/docusaurus-plugin-content-docs/current/concepts/public-api.md
  website/i18n/en/docusaurus-plugin-content-docs/current/get-started/basics.md
  website/i18n/en/docusaurus-plugin-content-docs/current/get-started/faq.md
  website/i18n/en/docusaurus-plugin-content-docs/current/get-started/motivation.md
  website/i18n/en/docusaurus-plugin-content-docs/current/get-started/overview.md
  website/i18n/en/docusaurus-plugin-content-docs/current/get-started/quick-start.md
  website/i18n/en/docusaurus-plugin-content-docs/current/guides/examples/viewer.md
  website/i18n/en/docusaurus-plugin-content-docs/current/guides/low-coupling.md
  website/i18n/en/docusaurus-plugin-content-docs/current/guides/migration-from-v1.md
  website/i18n/en/docusaurus-plugin-content-docs/current/readme.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/glossary.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/knowledge-types.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/app.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/entities.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/features.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/overview.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/pages.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/processes.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/shared.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/layers/widgets.md
  website/i18n/en/docusaurus-plugin-content-docs/current/reference/segments.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/concepts/app-splitting.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/basics.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/get-started/faq.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/guides/migration-from-v1.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/layers/features.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/layers/overview.md
  website/i18n/ru/docusaurus-plugin-content-docs/current/reference/layers/pages.md
Labels: help wanted, TYPE | workflow
